function this = Fuel(name,state,molarMass,fuel_O2,f, LEL, UEL, MEC)

if(~strcmp(state,'GAS') && ~strcmp(state,'SOLID'))
    error('The state shall be either GAS or SOLID');
end

this=struct( ...
    'name',name, ... 
    'state',state, ...
    'W', molarMass, ...
    'fuel_O2', fuel_O2, ...
    'f', f, ... volatiles fraction
    'LEL', LEL, ...
    'UEL', UEL, ...
    'MEC', MEC ...
    );

